### ISSUE TITLE
Full PlaceholderAPI support (relational placeholders)

### ISSUE THREAD

**Issue by mbax** [Draycia/Carbon#11]
In `PlaceholderAPI`:

```java
/**
   * set relational placeholders in the text specified placeholders are matched with the pattern
   * %<rel_(identifier)_(params)>% when set with this method
   *
   * @param one First player to compare
   * @param two Second player to compare
   * @param text Text to parse the placeholders in
   * @return The text containing the parsed relational placeholders
   */
  public static String setRelationalPlaceholders(Player one, Player two, String text) {
```

Example usage: Placeholders that provide different coloration based on relationships between players (enemy, ally, etc).

Exact example usage: FactionsUUID has %rel_factionsuuid_relation% for relation name and 
%rel_rel_factionsuuid_relation_relation_color% for a string of just the color for that relationship.

I regularly see users wanting a good chat plugin that supports this.

**Comment by Draycia** [comment]
(Should be) implemented as of f6078b9fc48c4cde7b92376b03c9adbe59976b2d
